### PR TITLE
Add json structure for basic weapons

### PR DESCRIPTION
**Pull request by TinySandwich**
These are some json weapon values added in for later use.

Note: I won't merge this till after the merge onto master is complete.

### CODE REVIEW

**Comment by Moguri** [comment]
Some thoughts:
* We should have `abilities` be a list of ability IDs (i.e., a list of strings) rather than a list of objects
* We should define schema for weapons
* I think all golems should have a basic attack by default, and we don't need to have this as an explicit ability on every weapon

**Comment by TinySandwich** [comment]
- Initially I did have the abilities as a list of strings, and then I came across "buff". My thought process is we either make "buff" a generic ability that can target a specified stat, or we make different "buff" abilities. Though since most abilities don't need this level of detail, outside of "description" or "title", I can see us reducing it down to a string.
a) Though if we're up for simplifying things further, drain/give HP/EP could be values passed into the "buff" ability.
b) "title" would be what we present the power to the user as (e.g. Sword's "buff" is titled "Rally").
- Yes, forgot about that part.
- I was thinking the same thing, then I realized not every weapon needs a basic attack. Heavier weapons like the mace only have heavy_attack. Thought this would be an interesting way to differentiate them.
a) I'm not married to the idea however and it would free up more ability slots of weapons that currently do have the basic attack option.
b) I would also make this attack based on the weapon not the golem, this way the basic attack can be treated the same as other abilities. It'd also let ranged weapons attack at range.
c) We may also need an unarmed weapon, that doesn't have any abilities.

**Comment by Moguri** [comment]
Abilities are easy to create so I do not believe complicating weapons to allow parameters on abilities (other than weapon strength and range) makes sense. If we want buffs to different stats, we can just make multiple abilities. Furthermore, I'd rather not need to gather multiple pieces of data to get access to something as simple as an ability description.

These json files will also need to specify where to find the weapon mesh.

**Comment by Moguri** [comment]
I fixed the linking issue and the invalid "pin" (the ability ID is "pin_down") for the bow. However, the mace is still using the invalid "heavy_attack". This is the last remaining error.

**Comment by TinySandwich** [comment]
@Moguri Looks like that fixed one of the failures, but now the knockback isn't working? :/

**Comment by Moguri** [comment]
Knockback still seems to work for me (tested with Gust). Merging this.

**Pull request merged**
